steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy scrape_cse_and_upload \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars BUCKET_NAME=cse-trading-pipeline-bucket \
          --entry-point scrape_cse_and_upload \
          --source cse_gcp_scraper

timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
