steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - scrape_cse_and_upload
      - --runtime=python311
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=BUCKET_NAME=cse-trading-pipeline-bucket
      - --entry-point=scrape_cse_and_upload
      - --source=cse_gcp_scraper
